version: "3.9"
services:
  web_front:
    build: sequence_interface
    ports:
      - "8501:8501"
    depends_on:
      - web_api
    networks:
      - mynet
  web_api:
    build: sequence_generator_examplev2
    ports:
      - "80"
    depends_on:
      - redis
    networks:
      - mynet
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web_api
    ports:
      - "80:80"
  redis:
    image: "redis:alpine"
    networks:
      - mynet

networks:
  mynet: